# Float and center settings and previews
windowrule = float on, stay_focused on, match:title ^(bluetui|Impala|Wiremix|org.gnome.NautilusPreviewer|Omarchy|About|btop)$
windowrule = center on, match:title ^(bluetui|Impala|Wiremix|org.gnome.NautilusPreviewer|Omarchy|About|btop|satty)$
windowrule = size 800 600, match:title ^(bluetui|Impala|Wiremix|org.gnome.NautilusPreviewer)$
windowrule = size (monitor_w*0.7) (monitor_h*0.8), match:title ^(btop|satty)$
windowrule = size 620 470, match:class Omarchy
windowrule = size 350 400, match:title ^(About)$

# Float and center file pickers
windowrule = tag +picker, match:class (xdg-desktop-portal-gtk|sublime_text)
windowrule = float on, center on, match:tag picker, match:title ^(Open.*Files?|Open Folder|Save.*Files?|All Files|Save)
windowrule = size 800 600, match:tag picker

# Fullscreen screensaver
windowrule = fullscreen on, match:class Screensaver

# No transparency on media windows
windowrule = opacity 1 1, match:class ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$
