

# Notion
windowrule = animation slide right, xray, initialTitle:^(ZapZap)$ 
windowrule = float, initialTitle:^(ZapZap)$
windowrule = center, initialTitle:^(ZapZap)$
windowrule = size 1200 800, initialTitle:^(ZapZap)$
windowrule = opacity 1 0.97, initialTitle:^(ZapZap)$
