"$schema" = 'https://starship.rs/config-schema.json'

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#dee3e5'
color_fg1 = "#babbf1"
color_bg1 = '#3c3836'
color_bg3 = '#756D53'
color_blue = '#2292A4'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.matugen]
color_fg0 = "#f0dfd7"
color_fg1 = "#babbf1"
color_bg1 = "#1a120d"
color_bg3 = '#756D53'
color_blue = '#2292A4'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'


format = """
[ ](bg:color_bg1)\
$os\
$username\
[](bg:color_fg0 fg:color_bg1)\
$directory\
[](bg:color_bg1 fg:color_fg0)\
$git_branch\
$git_status\
[](bg:color_bg1 fg:color_bg1)\
$c\
$cpp\
$rust\
$golang\
$nodejs(fg:color_bg1)\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$line_break\
$shell\
$character"""

add_newline = true



[os]
disabled = false
style = "bg:color_bg1 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_bg1 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg1 bg:color_fg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_bg1)]($style)'

[git_status]
style = "bg:color_bg1"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_bg1)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol( $version )](fg:color_fg0)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[character]
disabled = true
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
bash_indicator = ' '
zsh_indicator = ''
elvish_indicator = "Elvish"
unknown_indicator = ''
style = 'color_fg1 bold'
disabled = false

[line_break]
disabled = false
